from pyspark.sql import SparkSession

# Crear una sesión de Spark
spark = SparkSession.builder.appName("HelloWorld").getOrCreate()

# Ejecutar una consulta SQL
df = spark.sql("SELECT 'Hello World' as hello")

# Mostrar el resultado en consola
df.show()

# Guardar el resultado en un archivo JSON
df.write.mode("overwrite").json("results")







