name: spark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: ls -la  

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.3'
          hadoop-version: '3'

      - run: spark-submit --version

      
      - run: wget -O dataset.csv ${{ github.event.client_payload.dataseturl }}
      - run: wget -O app.py ${{ github.event.client_payload.codeurl }}
      - run: ls -la
      - run: spark-submit --master local app.py 

  
      - run: wget -O dataset.csv https://raw.githubusercontent.com/Lord17Charly/spark-labs/refs/heads/main/datasets/people.csv
      - run: ls -la
      - run: spark-submit --master local people.py

      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: save spark results
          CI_COMMIT_AUTHOR: Lord17Charly
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "gutierrezvottecarlos@gmail.com"
          git add results
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push


